final matkul = [
  "MA1101	Matematika I",
  "MA1102	Matematika II",
  "MA1103	Matematika Bisnis I",
  "MA1201	Matematika IIA (Sains dan Rekayasa)",
  "MA1202	Matematika IIB (Ilmu Hayati)",
  "MA1203	Matematika IIC (Rekayasa I)",
  "MA1204	Matematika IID (Rekayasa II)",
  "MA1205	Matematika IIE (Rekayasa III)",
  "MA1206	Matematika IIF (Bisnis dan Manajemen)",
  "MA2011	Topik Wawasan Matematika",
  "MA2021	Matriks dan Ruang Vektor",
  "MA2022	Struktur Bilangan Bulat",
  "MA2031	Matematika III",
  "MA2032	Kalkulus Lanjut",
  "MA2071	Matematika Sains",
  "MA2072	Matematika Rekayasa IA",
  "MA2074	Matematika Rekayasa IIA",
  "MA2075	Pengenalan Pemodelan Matematika",
  "MA2076	Matematika Rekayasa IIIB",
  "MA2077	Matematika Rekayasa IVB",
  "MA2081	Statistika Dasar",
  "MA2082	Biostatistika",
  "MA2111	Dasar-dasar Matematika",
  "MA2121	Aljabar Linier Elementer",
  "MA2122	Aljabar Linier Dasar",
  "MA2151	Simulasi dan Komputasi Matematika",
  "MA2174	Metode Persamaan Diferesial Parsial",
  "MA2181	Analisis Data",
  "MA2231	Kalkulus Peubah Banyak",
  "MA2251	Matematika Diskret",
  "MA2252	Pengantar Teori Bilangan",
  "MA2271	Pengantar Persamaan Diferensial",
  "MA2281	Statistika non parametrik",
  "MA2282	Metode Sampling",
  "MA3011	Karir dalam Matematika",
  "MA3021	Struktur Aljabar",
  "MA3022	Aljabar Linear",
  "MA3023	Aljabar Linear Numerik",
  "MA3032	Metode Fourier dan Wavelet",
  "MA3041	Peng. Geometri Diferensial",
  "MA3042	Geometri",
  "MA3051	Pengantar Teori Graf",
  "MA3052	Teori Graf Algoritmik",
  "MA3053	Pembelajaran Mesin",
  "MA3071	Pengantar Optimisasi",
  "MA3072	Metode Numerik",
  "MA3081	Statistika Matematika",
  "MA3082	Analisis Deret Waktu",
  "MA3083	Komputasi Statistik dengan R",
  "MA3084	Analisis dan Interpretasi Data",
  "MA3085	Analisis Spasial",
  "MA3091	Studi/Proyek Mandiri A",
  "MA3131	Pengantar Analisis Real",
  "MA3161	Pendahuluan Teori Suku Bunga",
  "MA3171	Matematika Numerik",
  "MA3172	Metode Matematika",
  "MA3181	Teori Peluang",
  "MA3182	Analisis Variansi dan Regresi",
  "MA3231	Pengantar Analisis Kompleks",
  "MA3261	Pengantar Matematika Keuangan",
  "MA3271	Pemodelan Matematika",
  "MA3282	Statistika Pengendalian Mutu",
  "MA4031	Fungsi Real",
  "MA4032	Kapita Selekta Analisis",
  "MA4041	Kapita Selekta Geometri",
  "MA4051	Teori Koding",
  "MA4052	Teori Permainan",
  "MA4071	Pengantar Sistem Dinamik",
  "MA4072	Pembelajaran Mendalam",
  "MA4073	Persamaan Diferensial Parsial",
  "MA4081	Analisis Data Kategori",
  "MA4091	Seminar Matematika I",
  "MA4092	Seminar Matematika II",
  "MA4093	Tugas Akhir I",
  "MA4094	Tugas Akhir II",
  "MA4095	Magang Kerja Praktik",
  "MA4096	Magang Lanjut I",
  "MA4097	Magang Lanjut II",
  "MA4098	Studi/Proyek Mandiri B",
  "MA4099	Studi/Proyek Mandiri C",
  "MA4121	Kapita Selekta Aljabar I",
  "MA4151	Kriptografi",
  "MA4152	Kapita Selekta Matematika Diskrit I",
  "MA4171	Teori Kontrol Linear",
  "MA4172	Kapita Selekta Mat. Terapan I",
  "MA4181	Pengantar Proses Stokastik",
  "MA4182	Kapita Selekta Statistika I",
  "MA4221	Kapita Selekta Aljabar II",
  "MA4252	Kapita Selekta Matematika Diskrit II",
  "MA4272	Kapita Selekta Mat. Terapan II",
  "MA4273	Metode Optimisasi",
  "MA4281	Analisis Multivariat",
  "MA4282	Kapita Selekta Statistika II",
  
  "FI1101	Fisika Dasar I",
  "FI1201	Fisika Dasar IIA",
  "FI1202	Fisika Dasar IIB",
  "FI1203	Fisika Dasar IIC",
  "FI1204	Laboratorium Fisika Dasar II",
  "FI2101	Fisika Matematik I",
  "FI2102	Mekanika",
  "FI2103	Fisika Modern dan Relativitas Khusus",
  "FI2104	Elektronika Analog dan Digital",
  "FI2121	Pengantar Fisika Material",
  "FI2151	Pemodelan, Generator Data, dan Analisisnya",
  "FI2171	Instrumentasi Berbasis Jaringan",
  "FI2201	Fisika Matematik II",
  "FI2202	Medan Elektromagnetik",
  "FI2203	Termodinamika",
  "FI2204	Eksperimen Elektromagnetika dan Termodinamika",
  "FI2205	Sistem Instrumentasi dan Metode Pengukuran",
  "FI2206	Fisika, Teknologi dan Masyarakat",
  "FI2211	Teori Relativitas Khusus",
  "FI2221	Pengantar Teknologi Optika dan Magnetika",
  "FI2231	Pengantar Sains dan Teknologi Nanomaterial",
  "FI2251	Biofisika",
  "FI2271	Sistem Sensor dan Aktuator",
  "FI2272	Visualisasi Data dan Pemrosesan Citra",
  "FI2281	Fisika Elektromagnetik",
  "FI2291	Energi dan Lingkungan",
  "FI3091	Kerja Praktek Kerja Praktik",
  "FI3092	Studi Mandiri Terpantau",
  "FI3093	Eksplorasi Fisika Terapan A Kerja Praktik",
  "FI3094	Eksplorasi Fisika Terapan B Kerja Praktik",
  "FI3095	Eksplorasi Fisika Terapan C Kerja Praktik",
  "FI3096	Eksplorasi Fisika Terapan D Kerja Praktik",
  "FI3097	Eksplorasi Fisika Terapan E Kerja Praktik",
  "FI3101	Mekanika Benda Terdeformasi dan Fluida",
  "FI3102	Gelombang",
  "FI3103	Metode Komputasi",
  "FI3104	Eksperimen Fisika Modern dan Optika",
  "FI3111	Teori Relativitas Umum",
  "FI3121	Fisika Material untuk Energi Terbarukan",
  "FI3131	Fisika dan Teknologi Material Maju",
  "FI3132	Pengenalan Industri Material Maju",
  "FI3141	Aplikasi dan Instrumentasi Nuklir",
  "FI3151	Fisika Radiasi dan Dosimetri",
  "FI3152	Elektrofisiologi dan Bioenergetika",
  "FI3161	Fisika Batuan dan Karakterisasi Lubangbor",
  "FI3162	Fisika Gunung api dan Panas bumi",
  "FI3163	Geosains untuk Fisika Bumi",
  "FI3171	Mikrokontroler dan Sistem Terintegrasi",
  "FI3172	Komputasi Granular dan Sistem Fisis",
  "FI3191	Sumber Energi",
  "FI3201	Fisika Kuantum",
  "FI3202	Fisika Statistik",
  "FI3203	Simulasi dan Pemodelan Sistem Fisis",
  "FI3204	Eksperimen Pengantar Penelitian Fisika",
  "FI3205	Scientific Communication",
  "FI3206	Fisika dalam Sistem Biologi",
  "FI3211	Teori Grup dalam Fisika",
  "FI3221	Teori dan Aplikasi Fotonik",
  "FI3222	Teknik Karakterisasi Material",
  "FI3231	Pengantar Aplikasi Energi Material Maju",
  "FI3232	Sintesis dan Karakterisasi Nanomaterial",
  "FI3241	Fisika Reaktor Nuklir",
  "FI3242	Manajemen Bahan Bakar Nuklir",
  "FI3251	Fisika Radiologi diagnostik dan intervensional",
  "FI3252	Praktikum Fisika Medis",
  "FI3261	Ekonofisika dan Sosiofisika",
  "FI3262	Eksplorasi Elektromagnetik Kebumian",
  "FI3263	Kecerdasan Buatan dan Nonlinearitas Bumi",
  "FI3264	Pencitraan Reservoir, Seismik dan Resistivitas",
  "FI3271	Analisis Data dengan Mesin Pembelajaran",
  "FI3272	Sistem Instrumentasi Cerdas",
  "FI3291	Konversi dan Sustainabilitas Energi",
  "FI4001	Fisika Zat Padat",
  "FI4002	Fisika Inti dan Partikel",
  "FI4003	Penyelesaian Problem dalam Fisika",
  "FI4011	Kapita Selekta Fisika Teoretik",
  "FI4091	Proposal Tugas Akhir",
  "FI4092	Tugas Akhir",
  "FI4111	Sistem Kuantum Terbuka dan Komputasi Kuantum",
  "FI4121	Sintesis dan Fungsionalisasi Material",
  "FI4122	Metode Kuantum untuk Material",
  "FI4131	Divais Elektronik dan Optoelektronik",
  "FI4141	Termal Hidrolik dan Keselamatan Nuklir",
  "FI4142	Keamanan dan Non-proliferasi Nuklir",
  "FI4151	Fisika Radioterapi",
  "FI4152	Fisika Kedokteran Nuklir",
  "FI4161	Inversi, Pemrosesan Sinyal dan Citra",
  "FI4171	Topik Khusus Instrumentasi dan Komputasi",
  "FI4172	Topik Khusus Sains Data Fisika",
  "FI4191	Topik Khusus Transisi Energi",
  "FI4221	Optika Kuantum dan Teknologinya",
  "FI4231	Kapita Selekta Teknologi Devais Kuantum",
  "FI4241	Topik Khusus Fisika Nuklir",
  "FI4242	Desain Sistem Energi Nuklir",
  "FI4251	Fisika Kesehatan dan Proteksi Radiasi",
  "FI4252	Radiobiologi",
  "FI4253	Anatomi dan Fisiologi",
  "FI4261	Fisika Lingkungan dan Migas Nonkonvensional",
  "FI4262	Mekanika Deformasi Batuan dan Geohazard",
  "FI4263	Lapangan Metode Fisika Bumi",
  "WI1111	Laboratorium Fisika Dasar",

  "AS2101	Astrofisika",
  "AS2102	Astrofisika Termal",
  "AS2103	Astronomi Posisi",
  "AS2104	Metode Matematika dalam Astronomi I",
  "AS2105	Astronomi Komputasi",
  "AS2201	Statistika dalam Astronomi",
  "AS2202	Proses Astrofisika I",
  "AS2203	Laboratorium Astronomi Dasar I",
  "AS2204	Metode Matematika dalam Astronomi II",
  "AS2205	Tata Surya",
  "AS3101	Fisika Gelombang",
  "AS3102	Mekanika Benda Langit",
  "AS3103	Laboratorium Astronomi Dasar II",
  "AS3104	Fisika Bintang",
  "AS3105	Proses Astrofisika II",
  "AS3106	Astronomi dan Lingkungan",
  "AS3107	Astrowisata",
  "AS3108	Sistem Kalender",
  "AS3109	Statistika dan Data Mining",
  "AS3201	Astrofisika Hidrodinamika",
  "AS3202	Pengantar Kosmologi",
  "AS3203	Fisika Galaksi",
  "AS3204	Astronomi Komputasi Lanjut",
  "AS3205	Benda Kecil Tata Surya",
  "AS3207	Lintasan Satelit",
  "AS4001 Kerja Astronomi Kerja Praktik",
  "AS4004	Kapita Selekta Astrofisika",
  "AS4005	Cuaca Antariksa",
  "AS4007	Evolusi Bintang",
  "AS4090	Tugas Akhir I Tugas Akhir / Tesis / Disertasi",
  "AS4091	Tugas Akhir II Tugas Akhir / Tesis / Disertasi",
  "AS4102	Sistem Bintang",
  "AS4103	Astrofisika Pengamatan",
  "AS4106	Ekstragalaksi",
  "AS4201	Materi Antar Bintang",
  "AS4202	Dinamika Sistem Bintang",
  "AS4203	Bintang Ganda Berinteraksi",
  "AS4204	Kosmologi Observasional",
  "AS4205	Eksoplanet",
  "AS4206	Astronomi Radio",

  "KI1101	Kimia Dasar I",
  "KI1201	Kimia Dasar 2A",
  "KI1202	Kimia Dasar 2B",
  "KI1203	Kimia Dasar 2C",
  "KI1204	Kimia Dasar 2D",
  "KI2042	Kimia Fisik",
  "KI2043	Praktikum Kimia Fisik",
  "KI2051	Kimia Organik",
  "KI2052	Kimia Sains Hayati",
  "KI2053	Praktikum Kimia Sains Hayati",
  "KI2121	Dasar-dasar Kimia Analitik",
  "KI2122	Praktikum Kimia Analitik",
  "KI2141	Struktur dan Ikatan Kimia",
  "KI2142	Kimia Fisik",
  "KI2151	Kimia Organik I",
  "KI2162	Biokimia Umum",
  "KI2163	Praktikum Biokimia Umum",
  "KI2164	Biokimia Umum",
  "KI2221	Cara-Cara Pemisahan dan Elektrometri",
  "KI2231	Struktur dan Kereaktifan Anorganik",
  "KI2241	Energetika Kimia",
  "KI2251	Kimia Organik II",
  "KI2252	Praktikum Kimia Organik",
  "KI2261	Dasar-dasar Kimia Hayati",
  "KI3011	Kemometri",
  "KI3012	Rancangan Penelitian",
  "KI3013	Manajemen Laboratorium Kimia",
  "KI3014	Prinsipia Kimia",
  "KI3015	Proyek Khusus",
  "KI3021	Metodologi Penelitian Kimia Analitik",
  "KI3043	Teknik Preparasi Sampel dan Pengolahan Data Spektroskopi",
  "KI3051	Pengantar Penelitian Kimia Organik",
  "KI3062	Pengantar Penelitian Biokimia",
  "KI3121	Analisis Spektrometri",
  "KI3131	Kimia Unsur Golongan Utama",
  "KI3141	Dinamika Kimia",
  "KI3142	Kimia Inti dan Radiasi",
  "KI3151	Sintesis Organik",
  "KI3152	Stereokimia dan Sintesis Asimetrik",
  "KI3161	Struktur dan Fungsi Biomolekul",
  "KI3162	Praktikum Struktur dan Fungsi Biomolekul",
  "KI3163	Pengantar Enzimologi",
  "KI3212	Elusidasi Struktur",
  "KI3213	Kimia Lingkungan",
  "KI3231	Logam Transisi dan Kimia Koordinasi",
  "KI3261	Metabolisme dan Informasi Genetik",
  "KI3262	Praktikum Metabolisme dan Informasi Genetika",
  "KI4011	Magang Industri Kerja Praktik 8",
  "KI4021	Kimia Forensik",
  "KI4022	Kimia Analitik Hijau",
  "KI4023	Keprofesian Kimia Analitik",
  "KI4031	Pengantar Metode Difraksi",
  "KI4032	Pengantar Katalisis",
  "KI4035	Kimia Anorganik Industri",
  "KI4044	Material Nano",
  "KI4052	Kimia Organik Industri",
  "KI4053	Kimia Hijau dalam Sintesis Obat",
  "KI4054	Kimia Kosmetik",
  "KI4055	Kimia Warna",
  "KI4091	Tugas Akhir I Tugas Akhir / Tesis / Disertasi",
  "KI4092	Tugas Akhir II Tugas Akhir / Tesis / Disertasi",
  "KI4093	Seminar Tugas Akhir dan Sidang Sarjana Tugas Akhir / Tesis / Diserasi",
  "KI4131	Pengantar Sintesis Anorganik",
  "KI4133	Karakterisasi Senyawa Anorganik",
  "KI4141	Kimia Polimer",
  "KI4156	Kimia Organik Hijau",
  "KI4161	Teknik dan Analisis Biomolekul",
  "KI4162	Struktur dan Rekayasa Protein",
  "KI4163	Lipid dan Membran biologi",
  "KI4164	Sidik Jari DNA",
  "KI4211	Kimia dan Masyarakat",
  "KI4212	Kerja Praktek Kerja Praktik",
  "KI4231	Pengantar Material Anorganik Fungsional",
  "KI4251	Dasar-dasar Fitokimia",
  "KI4261	Patologi Molekular dan Diagnostik",
  "KI4262	Pangan Fungsional",
  "KI4263	Transformasi karbohidrat",
  "WI1112 Laboratorium Kimia Dasar",

  "AK1260	Akuntansi I",
  "AK1264	Akuntansi",
  "AK2060	Akuntansi II",
  "AK2161	Teori Suku Bunga",
  "AK2163	Mikroekonomi",
  "AK2171	Metode Numerik Aktuaria",
  "AK2261	Pendahuluan Matematika Keuangan",
  "AK2263	Makroekonomi",
  "AK2281	Teori Peluang Aktuaria",
  "AK2282	Model Linier",
  "AK2283	Analisis Deret Waktu",
  "AK300X	Pengayaan Terarah A",
  "AK3063	Pembelajaran Mesin Aktuaria",
  "AK3081	Pengantar Model Kesintasan",
  "AK3092	Studi/Proyek Mandiri I",
  "AK3161	Pendahuluan Optimisasi Keuangan",
  "AK3183	Model Risiko I",
  "AK3185	Asuransi Jiwa I",
  "AK3261	Optimisasi Matematika Keuangan",
  "AK3281	Simulasi dan Pemodelan Aktuaria",
  "AK3283	Model Risiko II dan Simulasi",
  "AK3285	Asuransi Jiwa II",
  "AK3291	Lokakarya: Aplikasi Ilmu Aktuaria di Industri",
  "AK400X	Pengayaan Lanjut B",
  "AK4061	Keuangan Korporasi Aktuaria",
  "AK4062	Investasi dan Manajemen Aset",
  "AK4063	Matematika Keuangan Syariah",
  "AK4064	Model Matematika Perbankan",
  "AK4082	Model Linier Lanjut",
  "AK4091	Seminar Aktuaria I Tugas Akhir / Tesis / Disertasi",
  "AK4092	Seminar Aktuaria II Tugas Akhir / Tesis / Disertasi",
  "AK4093	Tugas Akhir I Tugas Akhir / Tesis / Disertasi",
  "AK4094	Tugas Akhir II Tugas Akhir / Tesis / Disertasi",
  "AK4095	Magang III",
  "AK4096	Studi/Proyek Mandiri II",
  "AK4097	Studi/Proyek Mandiri III",
  "AK4131	Kalkulus Stokastik",
  "AK4195	Magang I Kerja Praktik",
  "AK4295	Magang II Kerja Praktik",

  "EL1200	Pengantar Analisis Rangkaian",
  "EL2001	Rangkaian Elektrik",
  "EL2002	Sistem Digital",
  "EL2003	Struktur Diskrit",
  "EL2004	Probabilitas dan Statistika",
  "EL2005	Elektronika I",
  "EL2006	Material Teknik Elektro",
  "EL2007	Sinyal dan Sistem",
  "EL2008	Pemecahan Masalah dengan Pemrograman",
  "EL2101	Praktikum Rangkaian Elektrik",
  "EL2102	Praktikum Sistem Digital",
  "EL2150	Sistem Digital dan Mikroprosesor",
  "EL2205	Praktikum Elektronika I",
  "EL3009	Elektronika II",
  "EL3010	Pengolahan Sinyal Digital",
  "EL3011	Arsitektur Sistem Komputer",
  "EL3012	Sistem Mikroprosesor",
  "EL3013	Sistem Instrumentasi",
  "EL3014	Etika Profesi & Rekayasa",
  "EL3015	Sistem Kendali",
  "EL3016	Sistem Komunikasi",
  "EL3017	Sistem Tenaga Elektrik",
  "EL3112	Praktikum Sistem Mikroprosesor",
  "EL4001	Arsitektur Sistem Komputer II",
  "EL4002	Mikroelektronika RF",
  "EL4003	Perancangan Sistem Embedded",
  "EL4004	Sistem Penggerak Elektrik",
  "EL4005	Arsitektur & Komputasi Paralel",
  "EL4006	Jaringan Komputer",
  "EL4007	Pengolahan Citra Digital",
  "EL4011	Perancangan Elektronika Analog-Mixed-Signal",
  "EL4012	Analisis & Perancangan IC Digital",
  "EL4013	Perancangan Sistem VLSI",
  "EL4021	Devais Semikonduktor",
  "EL4022	Teknologi IC",
  "EL4023	Optoelektronika",
  "EL4031	Sistem Kendali Multivariabel",
  "EL4032	Dasar Sistem Kendali Cerdas",
  "EL4033	Robotika",
  "EL4034	Proyek Robotika",
  "EL4041	Perancangan Perangkat Lunak Jaringan",
  "EL4042	Teknik Enkripsi dan Keamanan",
  "EL4043	Teknologi dan Komputasi Kuantum",
  "EL4044	Perancangan Sistem IoT",
  "EL4045	Komputasi Performa Tinggi",
  "EL4060	Pengembangan Keprofesian dan Komunitas",
  "EL4061	Kapita Selekta Teknik Elektro",
  "EL4062	Inovasi dan Kewirausahaan dalam Rekayasa",
  "EL4063	Pengembangan Usaha dalam Rekayasa",
  "EL4064	Penelitian Rekayasa",
  "EL4065	Proyek Kerekayasaan Mandiri",
  "EL4071	Multidisiplin A",
  "EL4072	Multidisiplin B",
  "EL4073	Multidisiplin C",
  "EL4074	Multidisiplin D",
  "EL4075	Multidisiplin E",
  "EL4076	Multidisiplin F",
  "EL4077	Multidisiplin G",
  "EL4090	Proposal Proyek Akhir",
  "EL4091	Tugas Akhir Tugas Akhir / Tesis / Disertasi",
  "EL4092	Kerja Praktik Kerja Praktik",
  "EL4093	Magang di Industri Kerja Praktik 9",
  "EL4094	Pembelajaran Mandiri Teknik Elektro A",
  "EL4095	Pembelajaran Mandiri Teknik Elektro B 8",
  "EL4099	Praktikum Pilihan Teknik Elektro",

  "IF1210	Algoritma dan Pemrograman 1",
  "IF1220	Matematika Diskrit",
  "IF1221	Logika Komputasional",
  "IF1230	Organisasi dan Arsitektur Komputer",
  "IF2010	Pemrograman Berorientasi Objek",
  "IF2040	Pemodelan Basis Data",
  "IF2050	Dasar Rekayasa Perangkat Lunak",
  "IF2110	Algoritma dan Pemrograman 2",
  "IF2120	Probabilitas dan Statistika",
  "IF2123	Aljabar Linier dan Geometri",
  "IF2130	Sistem Operasi",
  "IF2150	Rekayasa Perangkat Lunak",
  "IF2180	Sosio-informatika dan Profesionalisme",
  "IF2211	Strategi Algoritma",
  "IF2224	Teori Bahasa Formal dan Otomata",
  "IF2230	Jaringan Komputer",
  "IF2240	Basis Data",
  "IF3070	Dasar Inteligensi Artifisial",
  "IF3110	Pengembangan Aplikasi Web",
  "IF3130	Sistem Paralel dan Terdistribusi",
  "IF3140	Sistem Basis Data",
  "IF3141	Sistem Informasi",
  "IF3151	Interaksi Manusia Komputer",
  "IF3170	Inteligensi Artifisial",
  "IF3210	Pengembangan Aplikasi Piranti Bergerak",
  "IF3211	Komputasi Domain Spesifik",
  "IF3250	Proyek Perangkat Lunak",
  "IF3270	Pembelajaran Mesin",
  "IF4010	Pemrograman Unit Pemrosesan Grafis",
  "IF4020	Kriptografi",
  "IF4021	Pemodelan dan Simulasi",
  "IF4031	Arsitektur Aplikasi Terdistribusi",
  "IF4033	Keamanan Siber",
  "IF4035	Blockchain",
  "IF4040	Pemodelan Data Lanjut",
  "IF4041	Penambangan Data",
  "IF4042	Sistem Temu Balik Informasi",
  "IF4044	Teknologi Big Data",
  "IF4050	Perkembangan dalam Rekayasa Perangkat Lunak",
  "IF4051	Pengembangan Sistem IoT",
  "IF4052	Komputasi Layanan",
  "IF4053	Keamanan Perangkat Lunak",
  "IF4054	Pengoperasian Sistem Perangkat Lunak",
  "IF4060	Rekayasa Interaksi",
  "IF4061	Visualisasi Data",
  "IF4062	Grafika Komputer",
  "IF4063	Gim dan Realitas Digital",
  "IF4070	Representasi Pengetahuan dan Penalaran",
  "IF4071	Pemrosesan Ucapan",
  "IF4072	Pemrosesan Bahasa Alami",
  "IF4073	Pemrosesan Citra Digital",
  "IF4074	Pembelajaran Mesin Lanjut",
  "IF4082	Pengembangan Keprofesian/Komunitas Informatika A",
  "IF4083	Pengembangan Keprofesian/Komunitas Informatika B",
  "IF4084	Pengembangan Keprofesian/Komunitas Informatika C",
  "IF4085	Topik Khusus Informatika A",
  "IF4086	Topik Khusus Informatika B",
  "IF4087	Topik Khusus Informatika C",
  "IF4088	Pengembangan Kemampuan Interpersonal",
  "IF4090	Kerja Praktik Kerja Praktik",
  "IF4091	Penyusunan Proposal",
  "IF4092	Tugas Akhir Tugas Akhir / Tesis / Disertasi",

  "EP1209	Dasar Pemrograman",
  "EP2001	Probabilitas dan Statistika",
  "EP2002	Sinyal & Sistem",
  "EP2003	Elektromagnetika",
  "EP2004	Sistem Pengukuran",
  "EP2005	Komputasi dan Analisis Numerik",
  "EP2051	Pengantar Teknik Tenaga Listrik",
  "EP2201	Praktikum Tenaga Listrik I",
  "EP3001	Mesin-Mesin Listrik",
  "EP3002	Analisis Sistem Tenaga",
  "EP3003	Material Elektroteknik",
  "EP3004	Elektronika Daya",
  "EP3005	Teknik Tegangan Tinggi",
  "EP3006	Proteksi Sistem Tenaga",
  "EP3007	Pembangkit Tenaga Listrik",
  "EP3008	Sistem Energi Cerdas",
  "EP3009	Pemanfaatan Energi Listrik",
  "EP3101	Praktikum Tenaga Listrik II",
  "EP3201	Praktikum Tenaga Listrik III",
  "EP4001	Kerja Praktik Kerja Praktik",
  "EP4002	Proposal Perancangan dan Seminar Tugas Akhir / Tesis / Disertasi",
  "EP4003	Tugas Akhir Perancangan Tugas Akhir / Tesis / Disertasi",
  "EP4011	Sistem Kendaraan Listrik",
  "EP4012	Sistem Penyimpanan Energi",
  "EP4021	Peralatan & Pengujian Tegangan Tinggi",
  "EP4022	Teknik Isolasi Peralatan Tegangan Tinggi",
  "EP4023	Pemeliharaan Peralatan Tegangan Tinggi",
  "EP4031	Pentanahan dan Proteksi Tegangan Lebih",
  "EP4032	Teknologi Rele",
  "EP4033	Sistem Distribusi Tenaga Listrik",
  "EP4034	SCADA & Manajemen Energi",
  "EP4041	Regulasi dan Kebijakan Energi",
  "EP4042	Pembangkit Energi Baru Terbarukan",
  "EP4080	Kapita Selekta Tenaga Listrik",
  "EP4081	Desain Sistem Tenaga Listrik",
  "EP4082	Rekayasa Sistem",
  "EP4083	Manajemen Proyek Sistem Kelistrikan",
  "EP4084	Penggunaan Motor Listrik",
  "EP4085	Etika Rekayasa",
  "EP4086	Aspek Keselamatan dalam Ketenagalistrikan",
  "EP4091	Magang Industri",
  "EP4092	Studi Independen Tenaga Listrik A",
  "EP4093	Studi Independen Tenaga Listrik B",
  "EP4094	Studi Independen Tenaga Listrik C",

  "ET1201	Matematika Diskrit",
  "ET1202	Rangkaian Listrik",
  "ET1203	Pemrograman",
  "ET2101	Probabilitas dan Statistik",
  "ET2102	Elektronika Telekomunikasi",
  "ET2103	Pengolahan Sinyal dalam Waktu Kontinyu",
  "ET2104	Jaringan Komputer",
  "ET2108	Praktikum Telekomunikasi I",
  "ET2201	Sistem Komunikasi",
  "ET2202	Elektromagnetika",
  "ET2203	Desain Sistem Digital",
  "ET2204	Pembelajaran Mesin untuk Telekomunikasi",
  "ET2208	Praktikum Telekomunikasi II",
  "ET2209	Praktikum Telekomunikasi III",
  "ET3101	Sistem Komunikasi Digital Modern",
  "ET3102	Saluran Transmisi dan Antena",
  "ET3103	Pengolahan Sinyal dalam Waktu Diskrit",
  "ET3104	Rekayasa Kinerja untuk Telekomunikasi",
  "ET3108	Praktikum Telekomunikasi IV",
  "ET3109	Praktikum Telekomunikasi V",
  "ET3201	Jaringan Optik",
  "ET3202	Jaringan Akses Nirkabel",
  "ET3203	Otomasi Jaringan dan Software Defined Networking",
  "ET3204	Layanan Tersambung dan Komputasi Awan",
  "ET3206	Etika Profesi",
  "ET3208	Praktikum Telekomunikasi VI",
  "ET4101	Kerja Praktek Kerja Praktik",
  "ET4102	Tugas Akhir I & Seminar",
  "ET4111	Sistem Antena",
  "ET4112	Devais Nirkabel",
  "ET4113	Elektronika Frekuensi Radio",
  "ET4114	Sistem Radar",
  "ET4115	Komputasi Elektromagnetik",
  "ET4116	Kompatibilitas Elektromagnetik",
  "ET4131	Ekonomi dan Regulasi Telekomunikasi",
  "ET4132	Kapita Selekta Telekomunikasi",
  "ET4133	Infrastruktur Blockchain",
  "ET4134	Named Data Networking",
  "ET4135	Keamanan Jaringan Telekomunikasi",
  "ET4202	Tugas Akhir II Tugas Akhir / Tesis / Disertasi",
  "ET4221	Sistem Komunikasi Satelit",
  "ET4222	Sistem Broadcasting",
  "ET4223	Komunikasi MIMO Masif",
  "ET4224	Komunikasi Kuantum dan Internet Kuantum",
  "ET4225	Software Radio",
  "ET4241	Cyber Physical System",
  "ET4242	Kompresi Video dan Komunikasi",
  "ET4243	Pembelajaran Mesin Lanjut untuk Telekomunikasi",
  "ET4244	Optimisasi untuk Telekomunikasi",
  "ET4301	Pengembangan Keprofesian/Komunitas Teknik Telekomunikasi A",
  "ET4302	Pengembangan Keprofesian/Komunitas Teknik Telekomunikasi B",
  "ET4303	Pengembangan Keprofesian/Komunitas Teknik Telekomunikasi C",
  "ET4304	Pengembangan Keprofesian/Komunitas Teknik Telekomunikasi D",
  "ET4305	Pengembangan Keprofesian/Komunitas Teknik Telekomunikasi E",
  "ET4306	Pengembangan Keprofesian/Komunitas Teknik Telekomunikasi F",
  "ET4307	Pengembangan Keprofesian/Komunitas Teknik Telekomunikasi G",

  "II1200	Pengantar Sistem dan Teknologi Informasi",
  "II2100	Komunikasi Interpersonal dan Publik",
  "II2110	Matematika Diskret",
  "II2120	Jaringan Komputer",
  "II2130	Sistem dan Arsitektur Komputer",
  "II2210	Teknologi Platform",
  "II2211	Probabilitas dan Statistik",
  "II2221	Analisis Kebutuhan Enterprise",
  "II2240	Sistem Multimedia",
  "II2250	Manajemen Basis Data",
  "II2260	Internet of Things",
  "II3120	Layanan Sistem dan Teknologi Informasi",
  "II3130	Arsitektur Enterprise",
  "II3131	Interaksi Manusia Komputer",
  "II3140	Pengembangan Aplikasi Web dan Mobile",
  "II3160	Teknologi Sistem Terintegrasi",
  "II3170	Hukum dan Etika Teknologi Informasi",
  "II3220	Tata Kelola Teknologi Informasi",
  "II3230	Keamanan Informasi",
  "II3240	Rekayasa Sistem dan Teknologi Informasi",
  "II4010	Manajemen Data",
  "II4011	Transformasi Digital",
  "II4012	Inteligensi Artifisial untuk Bisnis",
  "II4013	Data Analytics",
  "II4021	Kriptografi",
  "II4022	Rekayasa Privasi Digital",
  "II4023	Forensik Digital",
  "II4024	Hukum Siber",
  "II4050	Rekayasa Sistem Multimedia",
  "II4051	Manajemen Produk",
  "II4052	Analisis dan Perancangan Kinerja Sistem",
  "II4053	Audit Teknologi Informasi",
  "II4071	Pengembangan Keprofesian/Komunitas STI A",
  "II4072	Pengembangan Keprofesian/Komunitas STI B",
  "II4073	Pengembangan Keprofesian/Komunitas STI C",
  "II4074	Pengembangan Soft Skills STI",
  "II4075	Inovasi dan Studi Mandiri STI",
  "II4077	Pengembangan Wirausaha STI",
  "II4078	Penelitian STI",
  "II4079	Topik Khusus STI A",
  "II4080	Topik Khusus STI B",
  "II4081	Topik Khusus STI C",
  "II4090	Kerja Praktik Kerja Praktik",
  "II4091	Proposal Tugas Akhir",
  "II4092	Tugas Akhir Tugas Akhir / Tesis / Disertasi",

  "EB2101	Dasar Teknik Biomedis",
  "EB2102	Rangkaian Elektrik dan Elektronika",
  "EB2103	Sistem Digital dan Mikroprosesor",
  "EB2201	Anatomi dan Fisiologi Manusia",
  "EB2202	Elektronika Biomedis",
  "EB2203	Sinyal dan Sistem",
  "EB2204	Probabilitas dan Biostatistika",
  "EB2205	Komputasi dan Analisis Data Biomedis",
  "EB2209	Praktikum Teknik Biomedis 1",
  "EB3031	Pengukuran dan Instrumentasi Biomedis",
  "EB3032	Proyek Teknik Biomedis",
  "EB3101	Fisika Biomedis",
  "EB3102	Instrumentasi Biomedis",
  "EB3103	Pengolahan Sinyal Biomedis",
  "EB3104	Molekul, Sel, dan Organisme",
  "EB3109	Praktikum Teknik Biomedis 2",
  "EB3201	Biomekanika",
  "EB3202	Sistem Kendali Biomedis",
  "EB3203	Pengolahan Citra Biomedis",
  "EB3204	Pembelajaran Mesin dalam Teknik Biomedis",
  "EB3220	Perancangan Sistem Biomedis",
  "EB4004	Sistem Instrumentasi Biomedis",
  "EB4005	Pengolahan Sinyal Biomedis Lanjut",
  "EB4006	Sistem Pencitraan Biomedis",
  "EB4007	Sistem Informasi Kesehatan",
  "EB4008	Fenomena Transpor dalam Sistem Biomedis",
  "EB4009	Biomekanika Lanjut",
  "EB4010	Pemodelan dan Simulasi Sistem Biomedis",
  "EB4011	Pembelajaran Mesin Lanjut Teknik Biomedis",
  "EB4012	Biosensor",
  "EB4013	Asesmen dan Manajemen Teknologi Kesehatan",
  "EB4014	Bioelektromagnetika",
  "EB4015	Kapita Selekta Teknik Biomedis",
  "EB4040	Metode Penelitian dan Bioetika",
  "EB4080	Kerja Praktik dan Profesionalisme Kerja Praktik",
  "EB4081	Topik Khusus Teknik Biomedis A",
  "EB4082	Topik Khusus Teknik Biomedis B",
  "EB4083	Topik Khusus Teknik Biomedis C",
  "EB4090	Tugas Akhir Tugas Akhir / Tesis / Disertasi",
  "EB4120	Purwarupa Sistem Biomedis",
];

final test = [
  {
    "FMIPA": {
      "MA": {
        "MA1101": "Matematika I",
        "MA1102": "Matematika II",
        "MA1103": "Matematika Bisnis I",
        "MA1201": "Matematika IIA (Sains dan Rekayasa)",
        "MA1202": "Matematika IIB (Ilmu Hayati)",
        "MA1203": "Matematika IIC (Rekayasa I)",
        "MA1204": "Matematika IID (Rekayasa II)",
        "MA1205": "Matematika IIE (Rekayasa III)",
        "MA1206": "Matematika IIF (Bisnis dan Manajemen)",
        "MA2011": "Topik Wawasan Matematika",
        "MA2021": "Matriks dan Ruang Vektor",
        "MA2022": "Struktur Bilangan Bulat",
        "MA2031": "Matematika III",
        "MA2032": "Kalkulus Lanjut",
        "MA2071": "Matematika Sains",
        "MA2072": "Matematika Rekayasa IA",
        "MA2074": "Matematika Rekayasa IIA",
        "MA2075": "Pengenalan Pemodelan Matematika",
        "MA2076": "Matematika Rekayasa IIIB",
        "MA2077": "Matematika Rekayasa IVB",
        "MA2081": "Statistika Dasar",
        "MA2082": "Biostatistika",
        "MA2111": "Dasar-dasar Matematika",
        "MA2121": "Aljabar Linier Elementer",
        "MA2122": "Aljabar Linier Dasar",
        "MA2151": "Simulasi dan Komputasi Matematika",
        "MA2174": "Metode Persamaan Diferesial Parsial",
        "MA2181": "Analisis Data",
        "MA2231": "Kalkulus Peubah Banyak",
        "MA2251": "Matematika Diskret",
        "MA2252": "Pengantar Teori Bilangan",
        "MA2271": "Pengantar Persamaan Diferensial",
        "MA2281": "Statistika non parametrik",
        "MA2282": "Metode Sampling",
        "MA3011": "Karir dalam Matematika",
        "MA3021": "Struktur Aljabar",
        "MA3022": "Aljabar Linear",
        "MA3023": "Aljabar Linear Numerik",
        "MA3032": "Metode Fourier dan Wavelet",
        "MA3041": "Peng. Geometri Diferensial",
        "MA3042": "Geometri",
        "MA3051": "Pengantar Teori Graf",
        "MA3052": "Teori Graf Algoritmik",
        "MA3053": "Pembelajaran Mesin",
        "MA3071": "Pengantar Optimisasi",
        "MA3072": "Metode Numerik",
        "MA3081": "Statistika Matematika",
        "MA3082": "Analisis Deret Waktu",
        "MA3083": "Komputasi Statistik dengan R",
        "MA3084": "Analisis dan Interpretasi Data",
        "MA3085": "Analisis Spasial",
        "MA3091": "Studi/Proyek Mandiri A",
        "MA3131": "Pengantar Analisis Real",
        "MA3161": "Pendahuluan Teori Suku Bunga",
        "MA3171": "Matematika Numerik",
        "MA3172": "Metode Matematika",
        "MA3181": "Teori Peluang",
        "MA3182": "Analisis Variansi dan Regresi",
        "MA3231": "Pengantar Analisis Kompleks",
        "MA3261": "Pengantar Matematika Keuangan",
        "MA3271": "Pemodelan Matematika",
        "MA3282": "Statistika Pengendalian Mutu",
        "MA4031": "Fungsi Real",
        "MA4032": "Kapita Selekta Analisis",
        "MA4041": "Kapita Selekta Geometri",
        "MA4051": "Teori Koding",
        "MA4052": "Teori Permainan",
        "MA4071": "Pengantar Sistem Dinamik",
        "MA4072": "Pembelajaran Mendalam",
        "MA4073": "Persamaan Diferensial Parsial",
        "MA4081": "Analisis Data Kategori",
        "MA4091": "Seminar Matematika I",
        "MA4092": "Seminar Matematika II",
        "MA4093": "Tugas Akhir I",
        "MA4094": "Tugas Akhir II",
        "MA4095": "Magang Kerja Praktik",
        "MA4096": "Magang Lanjut I",
        "MA4097": "Magang Lanjut II",
        "MA4098": "Studi/Proyek Mandiri B",
        "MA4099": "Studi/Proyek Mandiri C",
        "MA4121": "Kapita Selekta Aljabar I",
        "MA4151": "Kriptografi",
        "MA4152": "Kapita Selekta Matematika Diskrit I",
        "MA4171": "Teori Kontrol Linear",
        "MA4172": "Kapita Selekta Mat. Terapan I",
        "MA4181": "Pengantar Proses Stokastik",
        "MA4182": "Kapita Selekta Statistika I",
        "MA4221": "Kapita Selekta Aljabar II",
        "MA4252": "Kapita Selekta Matematika Diskrit II",
        "MA4272": "Kapita Selekta Mat. Terapan II",
        "MA4273": "Metode Optimisasi",
        "MA4281": "Analisis Multivariat",
        "MA4282": "Kapita Selekta Statistika II"
      },
      "FI" : {
        "FI1101" : "Fisika Dasar I",
  "FI1201" : "Fisika Dasar IIA",
  "FI1202" : "Fisika Dasar IIB",
  "FI1203" : "Fisika Dasar IIC",
  "FI1204" : "Laboratorium Fisika Dasar II",
  "FI2101" : "Fisika Matematik I",
  "FI2102" : "Mekanika",
  "FI2103" : "Fisika Modern dan Relativitas Khusus",
  "FI2104" : "Elektronika Analog dan Digital",
  "FI2121" : "Pengantar Fisika Material",
  "FI2151" : "Pemodelan, Generator Data, dan Analisisnya",
  "FI2171" : "Instrumentasi Berbasis Jaringan",
  "FI2201" : "Fisika Matematik II",
  "FI2202" : "Medan Elektromagnetik",
  "FI2203" : "Termodinamika",
  "FI2204" : "Eksperimen Elektromagnetika dan Termodinamika",
  "FI2205" : "Sistem Instrumentasi dan Metode Pengukuran",
  "FI2206" : "Fisika, Teknologi dan Masyarakat",
  "FI2211" : "Teori Relativitas Khusus",
  "FI2221" : "Pengantar Teknologi Optika dan Magnetika",
  "FI2231" : "Pengantar Sains dan Teknologi Nanomaterial",
  "FI2251" : "Biofisika",
  "FI2271" : "Sistem Sensor dan Aktuator",
  "FI2272" : "Visualisasi Data dan Pemrosesan Citra",
  "FI2281" : "Fisika Elektromagnetik",
  "FI2291" : "Energi dan Lingkungan",
  "FI3091" : "Kerja Praktek Kerja Praktik",
  "FI3092" : "Studi Mandiri Terpantau",
  "FI3093" : "Eksplorasi Fisika Terapan A Kerja Praktik",
  "FI3094" : "Eksplorasi Fisika Terapan B Kerja Praktik",
  "FI3095" : "Eksplorasi Fisika Terapan C Kerja Praktik",
  "FI3096" : "Eksplorasi Fisika Terapan D Kerja Praktik",
  "FI3097" : "Eksplorasi Fisika Terapan E Kerja Praktik",
  "FI3101" : "Mekanika Benda Terdeformasi dan Fluida",
  "FI3102" : "Gelombang",
  "FI3103" : "Metode Komputasi",
  "FI3104" : "Eksperimen Fisika Modern dan Optika",
  "FI3111" : "Teori Relativitas Umum",
  "FI3121" : "Fisika Material untuk Energi Terbarukan",
  "FI3131" : "Fisika dan Teknologi Material Maju",
  "FI3132" : "Pengenalan Industri Material Maju",
  "FI3141" : "Aplikasi dan Instrumentasi Nuklir",
  "FI3151" : "Fisika Radiasi dan Dosimetri",
  "FI3152" : "Elektrofisiologi dan Bioenergetika",
  "FI3161" : "Fisika Batuan dan Karakterisasi Lubangbor",
  "FI3162" : "Fisika Gunung api dan Panas bumi",
  "FI3163" : "Geosains untuk Fisika Bumi",
  "FI3171" : "Mikrokontroler dan Sistem Terintegrasi",
  "FI3172" : "Komputasi Granular dan Sistem Fisis",
  "FI3191" : "Sumber Energi",
  "FI3201" : "Fisika Kuantum",
  "FI3202" : "Fisika Statistik",
  "FI3203" : "Simulasi dan Pemodelan Sistem Fisis",
  "FI3204" : "Eksperimen Pengantar Penelitian Fisika",
  "FI3205" : "Scientific Communication",
  "FI3206" : "Fisika dalam Sistem Biologi",
  "FI3211" : "Teori Grup dalam Fisika",
  "FI3221" : "Teori dan Aplikasi Fotonik",
  "FI3222" : "Teknik Karakterisasi Material",
  "FI3231" : "Pengantar Aplikasi Energi Material Maju",
  "FI3232" : "Sintesis dan Karakterisasi Nanomaterial",
  "FI3241" : "Fisika Reaktor Nuklir",
  "FI3242" : "Manajemen Bahan Bakar Nuklir",
  "FI3251" : "Fisika Radiologi diagnostik dan intervensional",
  "FI3252" : "Praktikum Fisika Medis",
  "FI3261" : "Ekonofisika dan Sosiofisika",
  "FI3262" : "Eksplorasi Elektromagnetik Kebumian",
  "FI3263" : "Kecerdasan Buatan dan Nonlinearitas Bumi",
  "FI3264" : "Pencitraan Reservoir, Seismik dan Resistivitas",
  "FI3271" : "Analisis Data dengan Mesin Pembelajaran",
  "FI3272" : "Sistem Instrumentasi Cerdas",
  "FI3291" : "Konversi dan Sustainabilitas Energi",
  "FI4001" : "Fisika Zat Padat",
  "FI4002" : "Fisika Inti dan Partikel",
  "FI4003" : "Penyelesaian Problem dalam Fisika",
  "FI4011" : "Kapita Selekta Fisika Teoretik",
  "FI4091" : "Proposal Tugas Akhir",
  "FI4092" : "Tugas Akhir",
  "FI4111" : "Sistem Kuantum Terbuka dan Komputasi Kuantum",
  "FI4121" : "Sintesis dan Fungsionalisasi Material",
  "FI4122" : "Metode Kuantum untuk Material",
  "FI4131" : "Divais Elektronik dan Optoelektronik",
  "FI4141" : "Termal Hidrolik dan Keselamatan Nuklir",
  "FI4142" : "Keamanan dan Non-proliferasi Nuklir",
  "FI4151" : "Fisika Radioterapi",
  "FI4152" : "Fisika Kedokteran Nuklir",
  "FI4161" : "Inversi, Pemrosesan Sinyal dan Citra",
  "FI4171" : "Topik Khusus Instrumentasi dan Komputasi",
  "FI4172" : "Topik Khusus Sains Data Fisika",
  "FI4191" : "Topik Khusus Transisi Energi",
  "FI4221" : "Optika Kuantum dan Teknologinya",
  "FI4231" : "Kapita Selekta Teknologi Devais Kuantum",
  "FI4241" : "Topik Khusus Fisika Nuklir",
  "FI4242" : "Desain Sistem Energi Nuklir",
  "FI4251" : "Fisika Kesehatan dan Proteksi Radiasi",
  "FI4252" : "Radiobiologi",
  "FI4253" : "Anatomi dan Fisiologi",
  "FI4261" : "Fisika Lingkungan dan Migas Nonkonvensional",
  "FI4262" : "Mekanika Deformasi Batuan dan Geohazard",
  "FI4263" : "Lapangan Metode Fisika Bumi",
  "WI1111" : "Laboratorium Fisika Dasar"
      },
      "AS" : {
  "AS2101" : "Astrofisika",
  "AS2102" : "Astrofisika Termal",
  "AS2103" : "Astronomi Posisi",
  "AS2104" : "Metode Matematika dalam Astronomi I",
  "AS2105" : "Astronomi Komputasi",
  "AS2201" : "Statistika dalam Astronomi",
  "AS2202" : "Proses Astrofisika I",
  "AS2203" : "Laboratorium Astronomi Dasar I",
  "AS2204" : "Metode Matematika dalam Astronomi II",
  "AS2205" : "Tata Surya",
  "AS3101" : "Fisika Gelombang",
  "AS3102" : "Mekanika Benda Langit",
  "AS3103" : "Laboratorium Astronomi Dasar II",
  "AS3104" : "Fisika Bintang",
  "AS3105" : "Proses Astrofisika II",
  "AS3106" : "Astronomi dan Lingkungan",
  "AS3107" : "Astrowisata",
  "AS3108" : "Sistem Kalender",
  "AS3109" : "Statistika dan Data Mining",
  "AS3201" : "Astrofisika Hidrodinamika",
  "AS3202" : "Pengantar Kosmologi",
  "AS3203" : "Fisika Galaksi",
  "AS3204" : "Astronomi Komputasi Lanjut",
  "AS3205" : "Benda Kecil Tata Surya",
  "AS3207" : "Lintasan Satelit",
  "AS4001" : "Kerja Astronomi Kerja Praktik",
  "AS4004" : "Kapita Selekta Astrofisika",
  "AS4005" : "Cuaca Antariksa",
  "AS4007" : "Evolusi Bintang",
  "AS4090" : "Tugas Akhir I Tugas Akhir / Tesis / Disertasi",
  "AS4091" : "Tugas Akhir II Tugas Akhir / Tesis / Disertasi",
  "AS4102" : "Sistem Bintang",
  "AS4103" : "Astrofisika Pengamatan",
  "AS4106" : "Ekstragalaksi",
  "AS4201" : "Materi Antar Bintang",
  "AS4202" : "Dinamika Sistem Bintang",
  "AS4203" : "Bintang Ganda Berinteraksi",
  "AS4204" : "Kosmologi Observasional",
  "AS4205" : "Eksoplanet",
  "AS4206" : "Astronomi Radio"
      },
      "KI" : {
        "KI1101" : "Kimia Dasar I",
  "KI1201" : "Kimia Dasar 2A",
  "KI1202" : "Kimia Dasar 2B",
  "KI1203" : "Kimia Dasar 2C",
  "KI1204" : "Kimia Dasar 2D",
  "KI2042" : "Kimia Fisik",
  "KI2043" : "Praktikum Kimia Fisik",
  "KI2051" : "Kimia Organik",
  "KI2052" : "Kimia Sains Hayati",
  "KI2053" : "Praktikum Kimia Sains Hayati",
  "KI2121" : "Dasar-dasar Kimia Analitik",
  "KI2122" : "Praktikum Kimia Analitik",
  "KI2141" : "Struktur dan Ikatan Kimia",
  "KI2142" : "Kimia Fisik",
  "KI2151" : "Kimia Organik I",
  "KI2162" : "Biokimia Umum",
  "KI2163" : "Praktikum Biokimia Umum",
  "KI2164" : "Biokimia Umum",
  "KI2221" : "Cara-Cara Pemisahan dan Elektrometri",
  "KI2231" : "Struktur dan Kereaktifan Anorganik",
  "KI2241" : "Energetika Kimia",
  "KI2251" : "Kimia Organik II",
  "KI2252" : "Praktikum Kimia Organik",
  "KI2261" : "Dasar-dasar Kimia Hayati",
  "KI3011" : "Kemometri",
  "KI3012" : "Rancangan Penelitian",
  "KI3013" : "Manajemen Laboratorium Kimia",
  "KI3014" : "Prinsipia Kimia",
  "KI3015" : "Proyek Khusus",
  "KI3021" : "Metodologi Penelitian Kimia Analitik",
  "KI3043" : "Teknik Preparasi Sampel dan Pengolahan Data Spektroskopi",
  "KI3051" : "Pengantar Penelitian Kimia Organik",
  "KI3062" : "Pengantar Penelitian Biokimia",
  "KI3121" : "Analisis Spektrometri",
  "KI3131" : "Kimia Unsur Golongan Utama",
  "KI3141" : "Dinamika Kimia",
  "KI3142" : "Kimia Inti dan Radiasi",
  "KI3151" : "Sintesis Organik",
  "KI3152" : "Stereokimia dan Sintesis Asimetrik",
  "KI3161" : "Struktur dan Fungsi Biomolekul",
  "KI3162" : "Praktikum Struktur dan Fungsi Biomolekul",
  "KI3163" : "Pengantar Enzimologi",
  "KI3212" : "Elusidasi Struktur",
  "KI3213" : "Kimia Lingkungan",
  "KI3231" : "Logam Transisi dan Kimia Koordinasi",
  "KI3261" : "Metabolisme dan Informasi Genetik",
  "KI3262" : "Praktikum Metabolisme dan Informasi Genetika",
  "KI4011" : "Magang Industri Kerja Praktik 8",
  "KI4021" : "Kimia Forensik",
  "KI4022" : "Kimia Analitik Hijau",
  "KI4023" : "Keprofesian Kimia Analitik",
  "KI4031" : "Pengantar Metode Difraksi",
  "KI4032" : "Pengantar Katalisis",
  "KI4035" : "Kimia Anorganik Industri",
  "KI4044" : "Material Nano",
  "KI4052" : "Kimia Organik Industri",
  "KI4053" : "Kimia Hijau dalam Sintesis Obat",
  "KI4054" : "Kimia Kosmetik",
  "KI4055" : "Kimia Warna",
  "KI4091" : "Tugas Akhir I Tugas Akhir / Tesis / Disertasi",
  "KI4092" : "Tugas Akhir II Tugas Akhir / Tesis / Disertasi",
  "KI4093" : "Seminar Tugas Akhir dan Sidang Sarjana Tugas Akhir / Tesis / Diserasi",
  "KI4131" : "Pengantar Sintesis Anorganik",
  "KI4133" : "Karakterisasi Senyawa Anorganik",
  "KI4141" : "Kimia Polimer",
  "KI4156" : "Kimia Organik Hijau",
  "KI4161" : "Teknik dan Analisis Biomolekul",
  "KI4162" : "Struktur dan Rekayasa Protein",
  "KI4163" : "Lipid dan Membran biologi",
  "KI4164" : "Sidik Jari DNA",
  "KI4211" : "Kimia dan Masyarakat",
  "KI4212" : "Kerja Praktek Kerja Praktik",
  "KI4231" : "Pengantar Material Anorganik Fungsional",
  "KI4251" : "Dasar-dasar Fitokimia",
  "KI4261" : "Patologi Molekular dan Diagnostik",
  "KI4262" : "Pangan Fungsional",
  "KI4263" : "Transformasi karbohidrat",
  "WI1112" : "Laboratorium Kimia Dasar"
      },
      "AK" : {
"AK1260" : "Akuntansi I",
  "AK1264" : "Akuntansi",
  "AK2060" : "Akuntansi II",
  "AK2161" : "Teori Suku Bunga",
  "AK2163" : "Mikroekonomi",
  "AK2171" : "Metode Numerik Aktuaria",
  "AK2261" : "Pendahuluan Matematika Keuangan",
  "AK2263" : "Makroekonomi",
  "AK2281" : "Teori Peluang Aktuaria",
  "AK2282" : "Model Linier",
  "AK2283" : "Analisis Deret Waktu",
  "AK300X" : "Pengayaan Terarah A",
  "AK3063" : "Pembelajaran Mesin Aktuaria",
  "AK3081" : "Pengantar Model Kesintasan",
  "AK3092" : "Studi/Proyek Mandiri I",
  "AK3161" : "Pendahuluan Optimisasi Keuangan",
  "AK3183" : "Model Risiko I",
  "AK3185" : "Asuransi Jiwa I",
  "AK3261" : "Optimisasi Matematika Keuangan",
  "AK3281" : "Simulasi dan Pemodelan Aktuaria",
  "AK3283" : "Model Risiko II dan Simulasi",
  "AK3285" : "Asuransi Jiwa II",
  "AK3291" : "Lokakarya: Aplikasi Ilmu Aktuaria di Industri",
  "AK400X" : "Pengayaan Lanjut B",
  "AK4061" : "Keuangan Korporasi Aktuaria",
  "AK4062" : "Investasi dan Manajemen Aset",
  "AK4063" : "Matematika Keuangan Syariah",
  "AK4064" : "Model Matematika Perbankan",
  "AK4082" : "Model Linier Lanjut",
  "AK4091" : "Seminar Aktuaria I Tugas Akhir / Tesis / Disertasi",
  "AK4092" : "Seminar Aktuaria II Tugas Akhir / Tesis / Disertasi",
  "AK4093" : "Tugas Akhir I Tugas Akhir / Tesis / Disertasi",
  "AK4094" : "Tugas Akhir II Tugas Akhir / Tesis / Disertasi",
  "AK4095" : "Magang III",
  "AK4096" : "Studi/Proyek Mandiri II",
  "AK4097" : "Studi/Proyek Mandiri III",
  "AK4131" : "Kalkulus Stokastik",
  "AK4195" : "Magang I Kerja Praktik",
  "AK4295" : "Magang II Kerja Praktik"
      }
    },
    "SITH": {},
    "SF": {},
    "FTTM": {},
    "FITB": {},
    "FTI": {},
    "STEI": {
      "EL" : {
"EL1200" : "Pengantar Analisis Rangkaian",
  "EL2001" : "Rangkaian Elektrik",
  "EL2002" : "Sistem Digital",
  "EL2003" : "Struktur Diskrit",
  "EL2004" : "Probabilitas dan Statistika",
  "EL2005" : "Elektronika I",
  "EL2006" : "Material Teknik Elektro",
  "EL2007" : "Sinyal dan Sistem",
  "EL2008" : "Pemecahan Masalah dengan Pemrograman",
  "EL2101" : "Praktikum Rangkaian Elektrik",
  "EL2102" : "Praktikum Sistem Digital",
  "EL2150" : "Sistem Digital dan Mikroprosesor",
  "EL2205" : "Praktikum Elektronika I",
  "EL3009" : "Elektronika II",
  "EL3010" : "Pengolahan Sinyal Digital",
  "EL3011" : "Arsitektur Sistem Komputer",
  "EL3012" : "Sistem Mikroprosesor",
  "EL3013" : "Sistem Instrumentasi",
  "EL3014" : "Etika Profesi & Rekayasa",
  "EL3015" : "Sistem Kendali",
  "EL3016" : "Sistem Komunikasi",
  "EL3017" : "Sistem Tenaga Elektrik",
  "EL3112" : "Praktikum Sistem Mikroprosesor",
  "EL4001" : "Arsitektur Sistem Komputer II",
  "EL4002" : "Mikroelektronika RF",
  "EL4003" : "Perancangan Sistem Embedded",
  "EL4004" : "Sistem Penggerak Elektrik",
  "EL4005" : "Arsitektur & Komputasi Paralel",
  "EL4006" : "Jaringan Komputer",
  "EL4007" : "Pengolahan Citra Digital",
  "EL4011" : "Perancangan Elektronika Analog-Mixed-Signal",
  "EL4012" : "Analisis & Perancangan IC Digital",
  "EL4013" : "Perancangan Sistem VLSI",
  "EL4021" : "Devais Semikonduktor",
  "EL4022" : "Teknologi IC",
  "EL4023" : "Optoelektronika",
  "EL4031" : "Sistem Kendali Multivariabel",
  "EL4032" : "Dasar Sistem Kendali Cerdas",
  "EL4033" : "Robotika",
  "EL4034" : "Proyek Robotika",
  "EL4041" : "Perancangan Perangkat Lunak Jaringan",
  "EL4042" : "Teknik Enkripsi dan Keamanan",
  "EL4043" : "Teknologi dan Komputasi Kuantum",
  "EL4044" : "Perancangan Sistem IoT",
  "EL4045" : "Komputasi Performa Tinggi",
  "EL4060" : "Pengembangan Keprofesian dan Komunitas",
  "EL4061" : "Kapita Selekta Teknik Elektro",
  "EL4062" : "Inovasi dan Kewirausahaan dalam Rekayasa",
  "EL4063" : "Pengembangan Usaha dalam Rekayasa",
  "EL4064" : "Penelitian Rekayasa",
  "EL4065" : "Proyek Kerekayasaan Mandiri",
  "EL4071" : "Multidisiplin A",
  "EL4072" : "Multidisiplin B",
  "EL4073" : "Multidisiplin C",
  "EL4074" : "Multidisiplin D",
  "EL4075" : "Multidisiplin E",
  "EL4076" : "Multidisiplin F",
  "EL4077" : "Multidisiplin G",
  "EL4090" : "Proposal Proyek Akhir",
  "EL4091" : "Tugas Akhir Tugas Akhir / Tesis / Disertasi",
  "EL4092" : "Kerja Praktik Kerja Praktik",
  "EL4093" : "Magang di Industri Kerja Praktik 9",
  "EL4094" : "Pembelajaran Mandiri Teknik Elektro A",
  "EL4095" : "Pembelajaran Mandiri Teknik Elektro B 8",
  "EL4099" : "Praktikum Pilihan Teknik Elektro"
      },
      "IF" : {
        "IF1210" : "Algoritma dan Pemrograman 1",
  "IF1220" : "Matematika Diskrit",
  "IF1221" : "Logika Komputasional",
  "IF1230" : "Organisasi dan Arsitektur Komputer",
  "IF2010" : "Pemrograman Berorientasi Objek",
  "IF2040" : "Pemodelan Basis Data",
  "IF2050" : "Dasar Rekayasa Perangkat Lunak",
  "IF2110" : "Algoritma dan Pemrograman 2",
  "IF2120" : "Probabilitas dan Statistika",
  "IF2123" : "Aljabar Linier dan Geometri",
  "IF2130" : "Sistem Operasi",
  "IF2150" : "Rekayasa Perangkat Lunak",
  "IF2180" : "Sosio-informatika dan Profesionalisme",
  "IF2211" : "Strategi Algoritma",
  "IF2224" : "Teori Bahasa Formal dan Otomata",
  "IF2230" : "Jaringan Komputer",
  "IF2240" : "Basis Data",
  "IF3070" : "Dasar Inteligensi Artifisial",
  "IF3110" : "Pengembangan Aplikasi Web",
  "IF3130" : "Sistem Paralel dan Terdistribusi",
  "IF3140" : "Sistem Basis Data",
  "IF3141" : "Sistem Informasi",
  "IF3151" : "Interaksi Manusia Komputer",
  "IF3170" : "Inteligensi Artifisial",
  "IF3210" : "Pengembangan Aplikasi Piranti Bergerak",
  "IF3211" : "Komputasi Domain Spesifik",
  "IF3250" : "Proyek Perangkat Lunak",
  "IF3270" : "Pembelajaran Mesin",
  "IF4010" : "Pemrograman Unit Pemrosesan Grafis",
  "IF4020" : "Kriptografi",
  "IF4021" : "Pemodelan dan Simulasi",
  "IF4031" : "Arsitektur Aplikasi Terdistribusi",
  "IF4033" : "Keamanan Siber",
  "IF4035" : "Blockchain",
  "IF4040" : "Pemodelan Data Lanjut",
  "IF4041" : "Penambangan Data",
  "IF4042" : "Sistem Temu Balik Informasi",
  "IF4044" : "Teknologi Big Data",
  "IF4050" : "Perkembangan dalam Rekayasa Perangkat Lunak",
  "IF4051" : "Pengembangan Sistem IoT",
  "IF4052" : "Komputasi Layanan",
  "IF4053" : "Keamanan Perangkat Lunak",
  "IF4054" : "Pengoperasian Sistem Perangkat Lunak",
  "IF4060" : "Rekayasa Interaksi",
  "IF4061" : "Visualisasi Data",
  "IF4062" : "Grafika Komputer",
  "IF4063" : "Gim dan Realitas Digital",
  "IF4070" : "Representasi Pengetahuan dan Penalaran",
  "IF4071" : "Pemrosesan Ucapan",
  "IF4072" : "Pemrosesan Bahasa Alami",
  "IF4073" : "Pemrosesan Citra Digital",
  "IF4074" : "Pembelajaran Mesin Lanjut",
  "IF4082" : "Pengembangan Keprofesian/Komunitas Informatika A",
  "IF4083" : "Pengembangan Keprofesian/Komunitas Informatika B",
  "IF4084" : "Pengembangan Keprofesian/Komunitas Informatika C",
  "IF4085" : "Topik Khusus Informatika A",
  "IF4086" : "Topik Khusus Informatika B",
  "IF4087" : "Topik Khusus Informatika C",
  "IF4088" : "Pengembangan Kemampuan Interpersonal",
  "IF4090" : "Kerja Praktik Kerja Praktik",
  "IF4091" : "Penyusunan Proposal",
  "IF4092" : "Tugas Akhir Tugas Akhir / Tesis / Disertasi"
      },
      "EP" : {
"EP1209" : "Dasar Pemrograman",
  "EP2001" : "Probabilitas dan Statistika",
  "EP2002" : "Sinyal & Sistem",
  "EP2003" : "Elektromagnetika",
  "EP2004" : "Sistem Pengukuran",
  "EP2005" : "Komputasi dan Analisis Numerik",
  "EP2051" : "Pengantar Teknik Tenaga Listrik",
  "EP2201" : "Praktikum Tenaga Listrik I",
  "EP3001" : "Mesin-Mesin Listrik",
  "EP3002" : "Analisis Sistem Tenaga",
  "EP3003" : "Material Elektroteknik",
  "EP3004" : "Elektronika Daya",
  "EP3005" : "Teknik Tegangan Tinggi",
  "EP3006" : "Proteksi Sistem Tenaga",
  "EP3007" : "Pembangkit Tenaga Listrik",
  "EP3008" : "Sistem Energi Cerdas",
  "EP3009" : "Pemanfaatan Energi Listrik",
  "EP3101" : "Praktikum Tenaga Listrik II",
  "EP3201" : "Praktikum Tenaga Listrik III",
  "EP4001" : "Kerja Praktik Kerja Praktik",
  "EP4002" : "Proposal Perancangan dan Seminar Tugas Akhir / Tesis / Disertasi",
  "EP4003" : "Tugas Akhir Perancangan Tugas Akhir / Tesis / Disertasi",
  "EP4011" : "Sistem Kendaraan Listrik",
  "EP4012" : "Sistem Penyimpanan Energi",
  "EP4021" : "Peralatan & Pengujian Tegangan Tinggi",
  "EP4022" : "Teknik Isolasi Peralatan Tegangan Tinggi",
  "EP4023" : "Pemeliharaan Peralatan Tegangan Tinggi",
  "EP4031" : "Pentanahan dan Proteksi Tegangan Lebih",
  "EP4032" : "Teknologi Rele",
  "EP4033" : "Sistem Distribusi Tenaga Listrik",
  "EP4034" : "SCADA & Manajemen Energi",
  "EP4041" : "Regulasi dan Kebijakan Energi",
  "EP4042" : "Pembangkit Energi Baru Terbarukan",
  "EP4080" : "Kapita Selekta Tenaga Listrik",
  "EP4081" : "Desain Sistem Tenaga Listrik",
  "EP4082" : "Rekayasa Sistem",
  "EP4083" : "Manajemen Proyek Sistem Kelistrikan",
  "EP4084" : "Penggunaan Motor Listrik",
  "EP4085" : "Etika Rekayasa",
  "EP4086" : "Aspek Keselamatan dalam Ketenagalistrikan",
  "EP4091" : "Magang Industri",
  "EP4092" : "Studi Independen Tenaga Listrik A",
  "EP4093" : "Studi Independen Tenaga Listrik B",
  "EP4094" : "Studi Independen Tenaga Listrik C"
      },
      "ET" : {
"ET1201" : "Matematika Diskrit",
  "ET1202" : "Rangkaian Listrik",
  "ET1203" : "Pemrograman",
  "ET2101" : "Probabilitas dan Statistik",
  "ET2102" : "Elektronika Telekomunikasi",
  "ET2103" : "Pengolahan Sinyal dalam Waktu Kontinyu",
  "ET2104" : "Jaringan Komputer",
  "ET2108" : "Praktikum Telekomunikasi I",
  "ET2201" : "Sistem Komunikasi",
  "ET2202" : "Elektromagnetika",
  "ET2203" : "Desain Sistem Digital",
  "ET2204" : "Pembelajaran Mesin untuk Telekomunikasi",
  "ET2208" : "Praktikum Telekomunikasi II",
  "ET2209" : "Praktikum Telekomunikasi III",
  "ET3101" : "Sistem Komunikasi Digital Modern",
  "ET3102" : "Saluran Transmisi dan Antena",
  "ET3103" : "Pengolahan Sinyal dalam Waktu Diskrit",
  "ET3104" : "Rekayasa Kinerja untuk Telekomunikasi",
  "ET3108" : "Praktikum Telekomunikasi IV",
  "ET3109" : "Praktikum Telekomunikasi V",
  "ET3201" : "Jaringan Optik",
  "ET3202" : "Jaringan Akses Nirkabel",
  "ET3203" : "Otomasi Jaringan dan Software Defined Networking",
  "ET3204" : "Layanan Tersambung dan Komputasi Awan",
  "ET3206" : "Etika Profesi",
  "ET3208" : "Praktikum Telekomunikasi VI",
  "ET4101" : "Kerja Praktek Kerja Praktik",
  "ET4102" : "Tugas Akhir I & Seminar",
  "ET4111" : "Sistem Antena",
  "ET4112" : "Devais Nirkabel",
  "ET4113" : "Elektronika Frekuensi Radio",
  "ET4114" : "Sistem Radar",
  "ET4115" : "Komputasi Elektromagnetik",
  "ET4116" : "Kompatibilitas Elektromagnetik",
  "ET4131" : "Ekonomi dan Regulasi Telekomunikasi",
  "ET4132" : "Kapita Selekta Telekomunikasi",
  "ET4133" : "Infrastruktur Blockchain",
  "ET4134" : "Named Data Networking",
  "ET4135" : "Keamanan Jaringan Telekomunikasi",
  "ET4202" : "Tugas Akhir II Tugas Akhir / Tesis / Disertasi",
  "ET4221" : "Sistem Komunikasi Satelit",
  "ET4222" : "Sistem Broadcasting",
  "ET4223" : "Komunikasi MIMO Masif",
  "ET4224" : "Komunikasi Kuantum dan Internet Kuantum",
  "ET4225" : "Software Radio",
  "ET4241" : "Cyber Physical System",
  "ET4242" : "Kompresi Video dan Komunikasi",
  "ET4243" : "Pembelajaran Mesin Lanjut untuk Telekomunikasi",
  "ET4244" : "Optimisasi untuk Telekomunikasi",
  "ET4301" : "Pengembangan Keprofesian/Komunitas Teknik Telekomunikasi A",
  "ET4302" : "Pengembangan Keprofesian/Komunitas Teknik Telekomunikasi B",
  "ET4303" : "Pengembangan Keprofesian/Komunitas Teknik Telekomunikasi C",
  "ET4304" : "Pengembangan Keprofesian/Komunitas Teknik Telekomunikasi D",
  "ET4305" : "Pengembangan Keprofesian/Komunitas Teknik Telekomunikasi E",
  "ET4306" : "Pengembangan Keprofesian/Komunitas Teknik Telekomunikasi F",
  "ET4307" : "Pengembangan Keprofesian/Komunitas Teknik Telekomunikasi G"
      },
      "II" : {
        "II1200" : "Pengantar Sistem dan Teknologi Informasi",
  "II2100" : "Komunikasi Interpersonal dan Publik",
  "II2110" : "Matematika Diskret",
  "II2120" : "Jaringan Komputer",
  "II2130" : "Sistem dan Arsitektur Komputer",
  "II2210" : "Teknologi Platform",
  "II2211" : "Probabilitas dan Statistik",
  "II2221" : "Analisis Kebutuhan Enterprise",
  "II2240" : "Sistem Multimedia",
  "II2250" : "Manajemen Basis Data",
  "II2260" : "Internet of Things",
  "II3120" : "Layanan Sistem dan Teknologi Informasi",
  "II3130" : "Arsitektur Enterprise",
  "II3131" : "Interaksi Manusia Komputer",
  "II3140" : "Pengembangan Aplikasi Web dan Mobile",
  "II3160" : "Teknologi Sistem Terintegrasi",
  "II3170" : "Hukum dan Etika Teknologi Informasi",
  "II3220" : "Tata Kelola Teknologi Informasi",
  "II3230" : "Keamanan Informasi",
  "II3240" : "Rekayasa Sistem dan Teknologi Informasi",
  "II4010" : "Manajemen Data",
  "II4011" : "Transformasi Digital",
  "II4012" : "Inteligensi Artifisial untuk Bisnis",
  "II4013" : "Data Analytics",
  "II4021" : "Kriptografi",
  "II4022" : "Rekayasa Privasi Digital",
  "II4023" : "Forensik Digital",
  "II4024" : "Hukum Siber",
  "II4050" : "Rekayasa Sistem Multimedia",
  "II4051" : "Manajemen Produk",
  "II4052" : "Analisis dan Perancangan Kinerja Sistem",
  "II4053" : "Audit Teknologi Informasi",
  "II4071" : "Pengembangan Keprofesian/Komunitas STI A",
  "II4072" : "Pengembangan Keprofesian/Komunitas STI B",
  "II4073" : "Pengembangan Keprofesian/Komunitas STI C",
  "II4074" : "Pengembangan Soft Skills STI",
  "II4075" : "Inovasi dan Studi Mandiri STI",
  "II4077" : "Pengembangan Wirausaha STI",
  "II4078" : "Penelitian STI",
  "II4079" : "Topik Khusus STI A",
  "II4080" : "Topik Khusus STI B",
  "II4081" : "Topik Khusus STI C",
  "II4090" : "Kerja Praktik Kerja Praktik",
  "II4091" : "Proposal Tugas Akhir",
  "II4092" : "Tugas Akhir Tugas Akhir / Tesis / Disertasi"
      },
      "EB": {
        "EB2101" : "Dasar Teknik Biomedis",
  "EB2102" : "Rangkaian Elektrik dan Elektronika",
  "EB2103" : "Sistem Digital dan Mikroprosesor",
  "EB2201" : "Anatomi dan Fisiologi Manusia",
  "EB2202" : "Elektronika Biomedis",
  "EB2203" : "Sinyal dan Sistem",
  "EB2204" : "Probabilitas dan Biostatistika",
  "EB2205" : "Komputasi dan Analisis Data Biomedis",
  "EB2209" : "Praktikum Teknik Biomedis 1",
  "EB3031" : "Pengukuran dan Instrumentasi Biomedis",
  "EB3032" : "Proyek Teknik Biomedis",
  "EB3101" : "Fisika Biomedis",
  "EB3102" : "Instrumentasi Biomedis",
  "EB3103" : "Pengolahan Sinyal Biomedis",
  "EB3104" : "Molekul, Sel, dan Organisme",
  "EB3109" : "Praktikum Teknik Biomedis 2",
  "EB3201" : "Biomekanika",
  "EB3202" : "Sistem Kendali Biomedis",
  "EB3203" : "Pengolahan Citra Biomedis",
  "EB3204" : "Pembelajaran Mesin dalam Teknik Biomedis",
  "EB3220" : "Perancangan Sistem Biomedis",
  "EB4004" : "Sistem Instrumentasi Biomedis",
  "EB4005" : "Pengolahan Sinyal Biomedis Lanjut",
  "EB4006" : "Sistem Pencitraan Biomedis",
  "EB4007" : "Sistem Informasi Kesehatan",
  "EB4008" : "Fenomena Transpor dalam Sistem Biomedis",
  "EB4009" : "Biomekanika Lanjut",
  "EB4010" : "Pemodelan dan Simulasi Sistem Biomedis",
  "EB4011" : "Pembelajaran Mesin Lanjut Teknik Biomedis",
  "EB4012" : "Biosensor",
  "EB4013" : "Asesmen dan Manajemen Teknologi Kesehatan",
  "EB4014" : "Bioelektromagnetika",
  "EB4015" : "Kapita Selekta Teknik Biomedis",
  "EB4040" : "Metode Penelitian dan Bioetika",
  "EB4080" : "Kerja Praktik dan Profesionalisme Kerja Praktik",
  "EB4081" : "Topik Khusus Teknik Biomedis A",
  "EB4082" : "Topik Khusus Teknik Biomedis B",
  "EB4083" : "Topik Khusus Teknik Biomedis C",
  "EB4090" : "Tugas Akhir Tugas Akhir / Tesis / Disertasi",
  "EB4120" : "Purwarupa Sistem Biomedis"
      }
    },
    "FTMD": {},
    "FTSL": {},
    "SAPPK": {},
    "FSRD": {},
    "SBM": {}
  }
];

final test1 = {
  "FMIPA": {
    "MA": {"MA1101": "Matematika I", "MA1102": "Matematika II"},
    "FI": {"FI1101": "Fisika Dasar I", "FI1201": "Fisika Dasar IIA"},
    "AS": {"AS2101": "Astrofisika", "AS2102": "Astrofisika Termal"},
    "KI": {"KI1101": "Kimia Dasar I", "KI1201": "Kimia Dasar 2A"},
    "AK": {"AK1260": "Akuntansi I", "AK1264": "Akuntansi"},
  },
  "SITH": {},
  "SF": {},
  "FTTM": {},
  "FITB": {},
  "FTI": {},
  "STEI": {
    "EL": {
      "EL1200": "Pengantar Analisis Rangkaian",
      "EL2001": "Rangkaian Elektrik",
    },
    "IF": {
      "IF1210": "Algoritma dan Pemrograman 1",
      "IF1220": "Matematika Diskrit",
    },
    "EP": {
      "EP1209": "Dasar Pemrograman",
      "EP2001": "Probabilitas dan Statistika",
    },
    "ET": {"ET1201": "Matematika Diskrit", "ET1202": "Rangkaian Listrik"},
    "II": {
      "II1200": "Pengantar Sistem dan Teknologi Informasi",
      "II2100": "Komunikasi Interpersonal dan Publik",
    },
    "EB": {
      "EB2101": "Dasar Teknik Biomedis",
      "EB2102": "Rangkaian Elektrik dan Elektronika",
    },
  },
  "FTMD": {},
  "FTSL": {},
  "SAPPK": {},
  "FSRD": {},
  "SBM": {},
};
