// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:ldte_stei_itb/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(GlobalConfigModelAdapter());
    registerAdapter(MataKuliahPraktikumModelAdapter());
    registerAdapter(StorageCacheModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(GlobalConfigModelAdapter());
    registerAdapter(MataKuliahPraktikumModelAdapter());
    registerAdapter(StorageCacheModelAdapter());
  }
}
