// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:eform_ldte/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(FakultasModelAdapter());
    registerAdapter(GlobalConfigModelAdapter());
    registerAdapter(MataKuliahPraktikumModelAdapter());
    registerAdapter(ProgramStudiModelAdapter());
    registerAdapter(StorageCacheModelAdapter());
    registerAdapter(UserPreferenceModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(FakultasModelAdapter());
    registerAdapter(GlobalConfigModelAdapter());
    registerAdapter(MataKuliahPraktikumModelAdapter());
    registerAdapter(ProgramStudiModelAdapter());
    registerAdapter(StorageCacheModelAdapter());
    registerAdapter(UserPreferenceModelAdapter());
  }
}
